Chevaleresk/Chevaleresk/Controllers/PanoramixController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Chevaleresk.Models;

namespace Chevaleresk.Controllers
{
    public class PanoramixController : Controller
    {
        private ChevalereskEntities db = new ChevalereskEntities();
        private JoueursRepository j = new JoueursRepository();

        // GET: Panoramix
        public ActionResult Index()
        {
            if (j.IsAlchemist(Convert.ToInt32(Session["playerID"])) && (bool)Session["playerConnected"])
            {
                var potion = db.Potion.Include(p => p.Items);
                return View(potion.ToList());
            }
            return PartialView("Error");
        }

        public ActionResult GetPotionInfo(int? potionId)
        {
            var filter = db.Potion
                .Where(p => p.Items.idItem == potionId).ToList();

            return PartialView("IndexPartial", filter);
        }

        //[ValidateAntiForgeryToken]
        public ActionResult ConcocterPotion(int id)
        {
            if (Session["playerID"] != null && (bool)Session["playerConnected"] && j.IsAlchemist(Convert.ToInt32(Session["playerID"])))
            {
                var playerID = Convert.ToInt32(Session["playerID"]);

                db.ConcocterPotion(playerID, id);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return PartialView("Error");
        }
    }
}

Chevaleresk/Chevaleresk/Views/Panoramix/Index.cshtml
@model IEnumerable<Chevaleresk.Models.Potion>

@{
    ViewBag.Title = "Index";
}

<style>
    .titre {
        margin-bottom: 2%;
    }

    .magasin_item {
        width: 5%;
        height: 60px;
        padding-left: 2%;
        color: white;
        font-family: 'Inter';
        font-size: 18px;
    }

    .image {
        width: 250px;
        height: 150px;
    }

    .goldCoins {
        color: gold
    }

    .filtre {
        color: white;
        font-family: "Monda";
        font-size: 14px;
        font-weight: 200;
        padding-top: 10%;
        padding-left: 10%;
    }

    .filtre_prix {
        color: black;
        font-family: "Monda";
        font-size: 14px;
        font-weight: 200;
        width: 100px
    }

    .zone_principale {
        width: 100%;
        float: right;
    }

    #nav_filtre {
        visibility: hidden;
        background-color: #252525;
        position: fixed;
        top: 0;
        padding-top: 90px;
        bottom: 0;
        left: 0px;
        height: 100%;
        width: 12%;
        z-index: 999;
        overflow-y: auto;
    }



        #nav_filtre.visible {
            visibility: visible;
        }


    .magasin_item {
        width: 5%;
        height: 60px;
        padding-left: 2%;
        color: white;
        font-family: 'Inter';
        font-size: 18px;
        padding-bottom: 1.5%;
    }

        .magasin_item a {
            text-decoration: none;
        }

        .magasin_item:hover {
            transform: scale(1.05);
            transition: transform 0.3s ease;
            filter: brightness(110%);
        }

    .image {
        width: 250px;
        height: 150px;
    }

    .goldCoins {
        color: gold
    }

    .texte {
        color: white;
        font-family: 'Monda';
        text-align: center;
    }

    #appliquer_filtre {
        position: absolute;
        left: 10%;
        top: 60%;
        background-color: #D44C4C;
        color: white;
        text-align: center;
        border-radius: 10px;
        border-color: transparent;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 2px;
        padding-bottom: 2px;
        font-family: 'Monda';
    }

    .filter-btn {
        color: #D44C4C;
        background-color: #393939;
        border-color: #393939;
    }

        .filter-btn:hover {
            background-color: #555;
            border-color: #555;
        }

    .search-bar {
        display: block;
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #f3f6f4;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.375rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        background-color: #393939;
        border-color: transparent;
    }

    .float-div {
        top: 10%;
        display: flex;
        flex-direction: column;
        align-items: center;
        max-width: 1000px;
        margin: auto;
        background-color: #2F2F2F;
        padding: 50px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
    }

    .potionBtn:hover {
        transition: transform 0.3s ease;
        filter: brightness(110%);
    }

    .bouton:hover {
        transform:scale(1.05);
        transition: transform 0.3s ease;
        filter: brightness(110%);
    }

    .disabled {
        cursor: not-allowed;
        opacity: 0.5;
    }
</style>


<div class="float-div">
    @*<h2 style=" font-size: 48px">Panoramix</h2>*@
    @*<h5 style="color: red; margin-bottom: 20px;">@ViewBag.MsgError</h5>*@
    <div id="dataPotion" style="margin-bottom:30px;">
        <h4 class="fade-effect" style="font-size: 34px; font-family: 'Monda';">Veuillez choisir une potion 🧪</h4>
    </div>
    <div style="max-height: 200px; overflow-x: auto;">
        <div style="display: flex; flex-wrap: wrap; gap: 20px;">
            @foreach (var potion in Model)
            {
                <div style="width: 100px; height: 100px;">
                    <button id="potion@(potion.idItem)" onclick="choisirPotion(@potion.idItem)" class="potionBtn" style="border-color: #D44C4C; border-width: 0px; background-color:transparent; margin: 0; padding: 0; width: 100%; height: 100%;">
                        <img src="data:image/png;base64,@Convert.ToBase64String(potion.Items.photo)" style="width:100%; height:100%;" />
                    </button>
                </div>
            }
        </div>
    </div>
</div>



    @*<div style="display: flex; flex-direction: row; gap: 30px;">*@
    <!--<div style="display: flex; flex-wrap: wrap; gap: 20px;">-->
    @*<div style="display: flex; flex-direction: column; gap: 20px;">*@
    <!--@foreach (var potion in Model)
            {
                <button id="potion@(potion.idItem)" onclick="choisirPotion(@potion.idItem)" style="border-color: #D44C4C; border-width: 0px; background-color:transparent; margin: 0; padding: 0; ">
                    <img src="data:image/png;base64,@Convert.ToBase64String(potion.Items.photo)" style="width:100px; height:100px; " />
                </button>
            }
        </div>
        <div id="dataPotion" style="margin-top:30px;">
            <h2>Veuillez choisir une potion.</h2>
        </div>
    </div>-->
    @*</div>*@


    @section Scripts{
        <script>
        function choisirPotion(id) {
        $("button[id^='potion']").css('border-width', '0px');

        $('#potion' + id).css('border-width', '3px');

        $.ajax({
            url: '@Url.Action("GetPotionInfo", "Panoramix")',
            type: 'GET',
            data: {
                potionId: id,
            },
            success: function(data) {
                $("#dataPotion").html(data);
            },
            error: function() {
            }
        });
    };
        </script>
    }

Chevaleresk/Chevaleresk/Views/Panoramix/IndexPartial.cshtml
@model IEnumerable<Chevaleresk.Models.Potion>

@{
    Chevaleresk.Models.ChevalereskEntities DB = new Chevaleresk.Models.ChevalereskEntities();
    var recettes = DB.Recette.ToList();
    var elements = DB.elements.ToList();
    Chevaleresk.Models.JoueursRepository j = new Chevaleresk.Models.JoueursRepository();
}

@foreach (var potion in Model)
{
    Chevaleresk.Models.elements e1;
    Chevaleresk.Models.elements e2;
    bool elementsValide = false;

    var recettePotion = recettes.Where(r => r.Potions_idItem == potion.idItem).FirstOrDefault();
    try
    {
        e1 = DB.elements.Where(e => e.idItem == recettePotion.Element_idItem).FirstOrDefault();
        e2 = DB.elements.Where(e => e.idItem == recettePotion.Element_idItem2).FirstOrDefault();
    }
    catch
    {
        e1 = null;
        e2 = null;
    }


    <div id="info-potion" style="display: flex; flex-direction: column; gap: 20px; max-width:400px">
        <h2 class="texte" style="display: flex; justify-content: center; align-items: center; border-bottom: 2px solid #D44C4C; padding-bottom: 5px; ">@potion.Items.nom</h2>
        <h4 class="texte">Effet: @potion.effet</h4>
        <h4 class="texte">Durée: @potion.duree secondes</h4>
        @if (e1 != null || e2 != null)
        {

            var qtE1 = j.GetQteItemInventaire((Convert.ToInt32(Session["playerID"])), e1.idItem);
            var qtE2 = j.GetQteItemInventaire((Convert.ToInt32(Session["playerID"])), e2.idItem);
            elementsValide = qtE1 >= recettePotion.qtElement && qtE2 >= recettePotion.qtElement ? true : false;

            <div style="display: flex; flex-direction: row;gap:10px; justify-content: center;">
                <div>
                    <img src="data:image/png;base64,@Convert.ToBase64String(e1.Items.photo)" style="width:120px; height:120px;" alt="@e1.Items.nom" />
                    <div style="background-color: #252525; max-width: 120px; display: flex; flex-direction: column; align-items: center;">
                        <span class="texte">
                            @Html.DisplayFor(model => e1.Items.nom)
                        </span>

                        <div style="display: flex; justify-content: center; align-items: center;">
                            <span class="texte">@j.GetQteItemInventaire((Convert.ToInt32(Session["playerID"])), e1.idItem)/@Html.DisplayFor(model => recettePotion.qtElement)</span>
                        </div>
                    </div>
                </div>
                <span> + </span>
                <div>
                    <img src="data:image/png;base64,@Convert.ToBase64String(e2.Items.photo)" style="width:120px; height:120px;" alt="@e2.Items.nom" />
                    <div style="background-color: #252525; max-width: 120px; display: flex; flex-direction: column; align-items: center;">
                        <span class="texte">
                            @Html.DisplayFor(model => e2.Items.nom)
                        </span>

                        <div style="display: flex; justify-content: center; align-items: center;">

                            <span class="texte">@j.GetQteItemInventaire((Convert.ToInt32(Session["playerID"])), e2.idItem)/@Html.DisplayFor(model => recettePotion.qtElement)</span>
                        </div>
                    </div>
                </div>


            </div>
        }

        @if (elementsValide)
        {
            <a href="/Panoramix/ConcocterPotion?id=@potion.idItem" class="bouton" style="padding-top:5px; padding-bottom:5px; background-color: #D44C4C; text-decoration: none; color: inherit;">Concocter</a>
        }
        else
        {
            <span style=" font-family: 'Monda'; text-align: center; padding-top: 5px; color: red; font-size: 14px">Vous n'avez pas le ou les éléments nécessaires pour concocter.</span>
            <a class="bouton disabled" style="padding-top:5px; padding-bottom:5px; background-color: #D44C4C; text-decoration: none; color: inherit;" disabled>Concocter</a>
        }

    </div>
}