Chevaleresk/Chevaleresk/Controllers/MarketController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Caching;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Chevaleresk.Models;
using Microsoft.Ajax.Utilities;

namespace Chevaleresk.Controllers
{
    public class MarketController : Controller
    {
        private ChevalereskEntities db = new ChevalereskEntities();
        private JoueursRepository jRepo = new JoueursRepository();
        private string msg = "";

        //GET: Market
        public ActionResult Index()
        {
            var magasin = db.Magasin.Include(m => m.Items);
            return View(magasin);
        }


        //POST: Filtre par type d'items

        public ActionResult GetFilteredItems(bool arme, bool armure, bool potion, bool element)
        {
            var filter = db.Magasin.Include(m => m.Items);

            var selectedFilters = new List<string>();
            if (arme)
            {
                selectedFilters.Add("A");
            }
            if (armure)
            {
                selectedFilters.Add("C");
            }
            if (potion)
            {
                selectedFilters.Add("P");
            }
            if (element)
            {
                selectedFilters.Add("E");
            }

            if (selectedFilters.Any())
            {
                filter = filter.Where(m => selectedFilters.Contains(m.Items.typeItem));
            }

            var filteredItems = filter.ToList();

            return PartialView("IndexPartial", filteredItems);
        }

        //POST: Filtre Recherche

        public ActionResult SearchItems(string searchString)
        {

            //Regex pour s'assurer que la recherche est valide (pas de caractères spéciaux)
            Regex regex = new Regex("^[a-zA-Z0-9]*$");
            if (!regex.IsMatch(searchString))
            {
                searchString = string.Empty;
            }

            var items = db.Items.Where(i => i.nom.Contains(searchString)).ToList();

            var filter = items.Select(item => item.Magasin).ToList();
            return PartialView("IndexPartial", filter);
        }

        // POST: Filtre prix

        public ActionResult GetItemsbyPrice(int? minPrice, int? maxPrice)
        {
            if (minPrice == null) { minPrice = 0; };
            if (maxPrice == null) { maxPrice = 10000; };

            var filter = db.Magasin
                .Where(m => m.Items.prix >= minPrice && m.Items.prix <= maxPrice)
                .ToList();

            return PartialView("IndexPartial", filter);
        }


        // GET: Market/Details/5
        public ActionResult Details(int? id, string status = "")
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Magasin magasin = db.Magasin.Find(id);
            if (magasin == null)
            {
                return HttpNotFound();
            }
            ViewBag.MsgError = status;
            return View(magasin);
        }

        // GET: Market/Create
        public ActionResult Create()
        {
            ViewBag.idItem = new SelectList(db.Items, "idItem", "nom");
            return View();
        }

        // POST: Market/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idItem")] Magasin magasin)
        {
            if (ModelState.IsValid)
            {
                db.Magasin.Add(magasin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idItem = new SelectList(db.Items, "idItem", "nom", magasin.idItem);
            return View(magasin);
        }

        // GET: Market/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Magasin magasin = db.Magasin.Find(id);
            if (magasin == null)
            {
                return HttpNotFound();
            }
            ViewBag.idItem = new SelectList(db.Items, "idItem", "nom", magasin.idItem);
            return View(magasin);
        }

        // POST: Market/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idItem")] Magasin magasin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(magasin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idItem = new SelectList(db.Items, "idItem", "nom", magasin.idItem);
            return View(magasin);
        }

        // GET: Market/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Magasin magasin = db.Magasin.Find(id);
            if (magasin == null)
            {
                return HttpNotFound();
            }
            return View(magasin);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjouterCritique(int idItem, int idJoueur, DateTime date, string Commentaire = "", int stars = 0)
        {
            Magasin magasin = db.Magasin.Find(idItem);
            if (magasin == null)
            {
                return PartialView("Error");
            }

            if ( stars < 1 || stars > 5)
            {
                //msg =  "Veuillez inscrire un commentaire et/ou un nombre d'étoile valide.";
                TempData["NotificationType"] = "error";
                TempData["NotificationMessage"] = $"Veuillez inscrire un nombre d'étoile valide. ";
                TempData["NotificationTitle"] = "Avis invalide";
                return RedirectToAction("Details", new { id = idItem, status = msg });
                //return PartialView("Error");
            }
            //db.Critique.Add(new Critique { idItem = idItem, idJoueur = idJoueur, nbEtoile = stars, date = date, Commentaire = Commentaire });


            db.laisserUnCommentaire(idItem, idJoueur, stars, Commentaire);
            TempData["NotificationType"] = "success";
            TempData["NotificationMessage"] = $"Votre avis a été ajouté avec succès!";
            TempData["NotificationTitle"] = "Ajout réussi!";
            return RedirectToAction("Details", new { id = idItem });
        }

        public ActionResult RetirerCommentaire(int idCommentaire)
        {
            Critique critique = db.Critique.Find(idCommentaire);
            var idJoueur = Convert.ToInt32(Session["playerID"]);

            if (critique == null)
            {
                return PartialView("Error");
            }

            var idItem = critique.idItem;

            if (critique.idJoueur == Convert.ToInt32(Session["playerID"]) || jRepo.IsAdmin(Convert.ToInt32(Session["playerID"])))
            {
                db.retirerCommentaire(idCommentaire);
                TempData["NotificationType"] = "success";
                TempData["NotificationMessage"] = $"Avis de {jRepo.GetAlias(idJoueur)} supprimé avec succès!";
                TempData["NotificationTitle"] = "Suppression réussi!";

                return RedirectToAction("Details", new { id = idItem });
            }

            return PartialView("Error");
        }



        // POST: Market/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Magasin magasin = db.Magasin.Find(id);
            db.Magasin.Remove(magasin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Chevaleresk/Chevaleresk/Views/Market/Create.cshtml
@model Chevaleresk.Models.Magasin

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Magasin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idItem, "idItem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idItem", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Chevaleresk/Chevaleresk/Views/Market/Delete.cshtml
@model Chevaleresk.Models.Magasin

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Magasin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Items.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Items.nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Chevaleresk/Chevaleresk/Views/Market/Edit.cshtml
@model Chevaleresk.Models.Magasin

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Magasin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idItem)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Chevaleresk/Chevaleresk/Views/Market/Index.cshtml
@model IEnumerable<Chevaleresk.Models.Magasin>

@{
    ViewBag.Title = "Index";
}

<style>
    .titre {
        margin-bottom: 2%;
        font-family: 'Monda';
    }

    .magasin_item {
        width: 5%;
        height: 60px;
        padding-left: 2%;
        color: white;
        font-family: 'Inter';
        font-size: 18px;
    }

    .image {
        width: 250px;
        height: 150px;
    }

    .goldCoins {
        color: gold
    }

    .filtre {
        color: white;
        font-family: "Monda";
        font-size: 14px;
        font-weight: 200;
        padding-top: 10%;
        padding-left: 10%;
    }

    .filtre_prix {
        color: black;
        font-family: "Monda";
        font-size: 14px;
        font-weight: 200;
        width: 100px
    }

    .zone_principale {
        width: 100%;
        float: right;
    }

    #nav_filtre {
        visibility: hidden;
        background-color: #252525;
        position: fixed;
        top: 0;
        padding-top: 90px;
        bottom: 0;
        left: 0px;
        height: 100%;
        width: 12%;
        z-index: 999;
        overflow-y: auto;
    }



        #nav_filtre.visible {
            visibility: visible;
        }


    .magasin_item {
        width: 5%;
        height: 60px;
        padding-left: 2%;
        color: white;
        font-family: 'Inter';
        font-size: 18px;
        padding-bottom: 1.5%;
    }
        .magasin_item a {
            text-decoration: none;
        }

        .magasin_item:hover {
            transform: scale(1.05); 
            transition: transform 0.3s ease; 
            filter:brightness(110%);
        }

    .image {
        width: 250px;
        height: 150px;
    }

    .goldCoins {
        color: gold
    }

    .texte {
        color: white;
        font-family: 'Monda';
    }

    #appliquer_filtre {
        position: absolute;
        left: 10%;
        top: 60%;
        background-color: #D44C4C;
        color: white;
        text-align: center;
        border-radius: 10px;
        border-color: transparent;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 2px;
        padding-bottom: 2px;
        font-family: 'Monda';
    }

    .filter-btn {
        color: #D44C4C;
        background-color: #393939;
        border-color: #393939;
    }

        .filter-btn:hover {
            background-color: #555;
            border-color: #555;
        }

    .search-bar {
        display: block;
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #f3f6f4;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.375rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        background-color: #393939;
        border-color: transparent;
    }
</style>

<script>

    function filtre() {
        var filtre = document.getElementById("nav_filtre");
        var zonePrincipale = document.querySelector(".zone_principale");

        if (filtre.classList.contains("visible")) {
            filtre.classList.remove("visible");
            zonePrincipale.style.width = "100%";
        } else {
            filtre.classList.add("visible");
            zonePrincipale.style.width = "90%";
        }
    }
</script>
<div id="nav_filtre" class="texte">
    <div>
        <label class="filtre" for="Armes">
            Armes
            <input class="filtre" type="checkbox" id="cbArmes" name="typeItem" title="Armes" value="A" />
        </label>
    </div>
    <div>
        <label class="filtre" for="Armures">
            Armures
            <input class="filtre" type="checkbox" id="cbArmures" name="typeItem" title="Armures" value="C" />
        </label>
    </div>
    <div>
        <label class="filtre" for="Potions">
            Potions
            <input class="filtre" type="checkbox" id="cbPotions" name="typeItem" title="Potions" value="P" />
        </label>
    </div>
    <div>
        <label class="filtre" for="Elements">
            Éléments
            <input class="filtre" type="checkbox" id="cbElements" name="typeItem" title="Éléments" value="E" />
        </label>
    </div>
    <div>

        <label class="filtre" for="PrixMinimum">
            Prix minimum
            <input class="filtre_prix" type="number" id="PrixMinimum" min="0" max="10000" name="prixItem" title="Prix Minimum" />
        </label>
    </div>
    <div>
        <label class="filtre" for="PrixMaximum">
            Prix maximum
            <input class="filtre_prix" type="number" id="PrixMaximum" min="0" max="10000" name="prixItem" title="Prix Maximum" />
        </label>
        <input type="submit" id="appliquer_filtre" title="Appliquer" name="Appliquer" value="Appliquer">

    </div>
</div>
<div class="zone_principale">
    <div class="container" style="margin-bottom: 5%;">
        <h2 class="titre">Magasin</h2>
        <div class="row align-items-center">
            <div class="col-md-1">
                <button onclick="filtre()" class="btn btn-dark filter-btn">≡</button>
            </div>
            <div class="col-md-10" style="margin-left: -4%;">
                <div class="d-flex align-items-center">
                    <input id="searchInput" class="search-bar" placeholder="Recherche" type="text" />
                    <button id="searchBtn" class="btn btn-dark filter-btn ml-2" style="margin-left: 0.5%;">
                        <i class="fas fa-search" style="color:#f3f6f4"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>


<table id="dataItems">
    @Html.Partial("IndexPartial", Model)
</table>
    </div>

@section Scripts{
    <script>

    //Filtre Search
    $(document).ready(function() {
         $('#searchBtn').click(function() {
            var searchStr = $('#searchInput').val();

            $.ajax({
                url: '@Url.Action("SearchItems", "Market")',
                type: 'GET',
                data: { searchString: searchStr },
                success: function(data) {
                    $('#dataItems').html(data);
                 },
                error: function() {
                     /*console.log("");*/
                 }
            });
        });
    });




    //Filtre type item
    $(document).ready(function() {
        $('input[type="checkbox"][name="typeItem"]').on('change', function () {
            var selectedTypes = $('input[type="checkbox"][name="typeItem"]:checked').map(function () {
                return $(this).val();
            }).get();

            if (selectedTypes.length === 0 || selectedTypes == null) {
                selectedTypes = ["A", "C", "P", "E"];
            }

            $.ajax({
                url: '@Url.Action("GetFilteredItems", "Market")',
                type: 'GET',
                data: { arme: selectedTypes.includes("A"), armure: selectedTypes.includes("C"), potion: selectedTypes.includes("P"), element: selectedTypes.includes("E") },
                success: function (data) {
                    $("#dataItems").html(data);
                },
                error: function () {
                    //console.log("");
                }
            });
        });
    });


    //Filtrer Prix
    $(document).ready(function () {
        function filterItems(minPrice, maxPrice) {
            $.ajax({
                url:  '@Url.Action("GetItemsbyPrice", "Market")',
                type: 'GET',
                data: {
                    minPrice: minPrice,
                    maxPrice: maxPrice
                },
                success: function (data) {
                    $("#dataItems").html(data);
                },
                error: function () {
                     //console.log("");
                }
            });
        }

        $('#appliquer_filtre').click(function (e) {
            e.preventDefault(); 

            var minPrice = $('#PrixMinimum').val();
            var maxPrice = $('#PrixMaximum').val();

            filterItems(minPrice, maxPrice);
        });
    });
    </script>
}

Chevaleresk/Chevaleresk/Views/Market/IndexPartial.cshtml
@model IEnumerable<Chevaleresk.Models.Magasin>

@{ 
    int compteur = 0;
}

@foreach (var item in Model)
{
    if (compteur % 4 == 0)
    {
        @:<tr>
    }
              <td class="magasin_item">
                  <a href="@Url.Action("Details", "Market", new { id = item.Items.idItem })">
                      <div>
                          <img src="data:image/png;base64,@Convert.ToBase64String(item.Items.photo)" style="width:200px; height:200px; " />
                      </div>

                      <div style="background-color: #252525; max-width: 200px; display: flex; flex-direction: column; align-items: center;">
                          <span class="texte">
                              @Html.DisplayFor(model => item.Items.nom)
                          </span>

                          <div style="display: flex; justify-content: center; align-items: center;">
                              <span class="texte">@Html.DisplayFor(model => item.Items.prix) <span class="goldCoins cmdIcon fa fa-coins"></span></span>
                          </div>
                      </div>
                      </a>
              </td>

    compteur++;

    if (compteur % 4 == 0)
    {
        @:</tr>
    }
}

@if (compteur % 4 != 0)
{
    @:</tr>
}