Chevaleresk/Chevaleresk/Controllers/EnigmaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Chevaleresk.Models;

namespace Chevaleresk.Controllers
{
    public class EnigmaController : Controller
    {
        private ChevalereskEntities db = new ChevalereskEntities();

        // GET: Enigma
        public ActionResult Index()
        {
            if (Session["playerID"] != null && (bool)Session["playerConnected"])
            {
                var questions = db.Questions.Include(q => q.Categories);
                return View(questions.ToList());
            }
            else { return Redirect(@Url.Action("Login", "Accounts")); }
        }

        // GET: Enigma
        public ActionResult Jouer()
        {
            var questions = db.Questions.Include(q => q.Categories);
            var questionsList = questions.ToList();
            //var qstFiltre = questionsList.Where(q => q.type == type).ToList();
            Random random = new Random();
            var qstRdm = random.Next(questionsList.Count);
            var randomQuestion = questionsList[qstRdm];



            //var randomQuestion = db.questionRandom().ToList();
            return View(randomQuestion);
        }

        // GET: Enigma/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Questions questions = db.Questions.Find(id);
            if (questions == null)
            {
                return HttpNotFound();
            }
            return View(questions);
        }

        // GET: Enigma/Create
        public ActionResult Create()
        {
            ViewBag.idCategorie = new SelectList(db.Categories, "idCategories", "nomCategorie");
            return View();
        }

        // POST: Enigma/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idQuestion,enonce,type,idCategorie")] Questions questions)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(questions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idCategorie = new SelectList(db.Categories, "idCategories", "nomCategorie", questions.idCategorie);
            return View(questions);
        }

        // GET: Enigma/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Questions questions = db.Questions.Find(id);
            if (questions == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCategorie = new SelectList(db.Categories, "idCategories", "nomCategorie", questions.idCategorie);
            return View(questions);
        }

        // POST: Enigma/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idQuestion,enonce,type,idCategorie")] Questions questions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(questions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCategorie = new SelectList(db.Categories, "idCategories", "nomCategorie", questions.idCategorie);
            return View(questions);
        }

        // GET: Enigma/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Questions questions = db.Questions.Find(id);
            if (questions == null)
            {
                return HttpNotFound();
            }
            return View(questions);
        }

        // POST: Enigma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Questions questions = db.Questions.Find(id);
            db.Questions.Remove(questions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult GetEnigmaQuestion(string type)
        {
            var questions = db.Questions.Include(q => q.Categories);
            var questionsList = questions.ToList();

            Random random = new Random();
            List<Questions> qstFiltre;

            const string typeRandom = "R";
            const string typeEasy = "F";
            const string typeMedium = "M";
            const string typeHard = "D";

            switch (type)
            {
                case typeEasy:
                    qstFiltre = questionsList.Where(q => q.type == "F").ToList();
                    break;
                case typeMedium:
                    qstFiltre = questionsList.Where(q => q.type == "M").ToList();
                    break;
                case typeHard:
                    qstFiltre = questionsList.Where(q => q.type == "D").ToList();
                    break;
                case typeRandom:
                    qstFiltre = questionsList;
                    break;
                default:
                    qstFiltre = questionsList;
                    break;
            }

            //if (type == typeEasy)
            //{
            //    qstFiltre = questionsList.Where(q => q.type == "F").ToList();
            //}
            //if (type == typeMedium)
            //{
            //    qstFiltre = questionsList.Where(q => q.type == "M").ToList();
            //}
            //if (type == typeHard)
            //{
            //    qstFiltre = questionsList.Where(q => q.type == "D").ToList();
            //}
            //else
            //{
            //    qstFiltre = questionsList;
            //}


            var qstRdm = random.Next(qstFiltre.Count() );
            var randomQuestion = qstFiltre[qstRdm];

            return PartialView("QuestionPartial", randomQuestion);
        }

        public ActionResult ValidateEnigmaQuestion(int idJoueur, int idReponse, string typeQuestion)
        {
            try
            {
                //Joueurs playerBefore = db.Joueurs.Where(j => j.idJoueur == idJoueur).FirstOrDefault();
                //bool Alchemist
                
                const string typeEasy = "F";
                const string typeMedium = "M";
                const string typeHard = "D";

                Reponses rep = db.Reponses.Where(r => r.idReponse == idReponse).FirstOrDefault();
                Questions question = db.Questions.Where(q=>q.idQuestion == rep.idQuestion).FirstOrDefault();
                Categories categorie = db.Categories.Where(c=>c.idCategories == question.idCategorie).FirstOrDefault();
                var idCategorie = categorie.idCategories;

                var estCorrect = new ObjectParameter("estCorrect", typeof(int));
                db.vérifierReponse(idReponse, idJoueur, estCorrect);
                bool reponse = (bool)estCorrect.Value;
                int winningAmmount = 0;
                switch (typeQuestion)
                {
                    case typeEasy:
                        winningAmmount = 50;
                        break;
                    case typeMedium:
                        winningAmmount = 100;
                        break;
                    case typeHard:
                        winningAmmount = 200;
                        break;
                }

                TempData["playerWon"] = reponse;
                if (reponse)
                {
                    if(idCategorie == 1)
                    {
                        db.MonterAlchimiste(idJoueur);
                        //bool playerAfter = 
                    }
                    //var stats = db.Statistiques.Where(s => s.idJoueur == idJoueur).FirstOrDefault();
                    //if(stats != null)
                    //{
                    //    db.augmenterStats(idJoueur);
                    //}
                    //else
                    //{
                    //    Statistiques newStats = new Statistiques();
                    //    newStats.idJoueur = idJoueur;
                    //    newStats.nbQuestionReussi = 1;
                    //    newStats.nbQuestionEchoue = 0;
                    //    db.Statistiques.Add(newStats);
                    //    db.SaveChanges();
                    //}
                    TempData["winningMessage"] = $"Vous avez gagné {winningAmmount} écus!";
                }
                //else
                //{
                //    var stats = db.Statistiques.Where(s => s.idJoueur == idJoueur).FirstOrDefault();
                //    if (stats != null)
                //    {
                //        db.diminuerStats(idJoueur);
                //    }
                //    else
                //    {
                //        Statistiques newStats = new Statistiques();
                //        newStats.idJoueur = idJoueur;
                //        newStats.nbQuestionEchoue = 1;
                //        newStats.nbQuestionReussi = 0;

Chevaleresk/Chevaleresk/Views/Enigma/Create.cshtml
@model Chevaleresk.Models.Questions

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Questions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.enonce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.enonce, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.enonce, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idCategorie, "idCategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Chevaleresk/Chevaleresk/Views/Enigma/Delete.cshtml
@model Chevaleresk.Models.Questions

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Questions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.enonce)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enonce)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories.nomCategorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.nomCategorie)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Chevaleresk/Chevaleresk/Views/Enigma/Details.cshtml
@model Chevaleresk.Models.Questions

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Questions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.enonce)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enonce)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories.nomCategorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.nomCategorie)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idQuestion }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Chevaleresk/Chevaleresk/Views/Enigma/Edit.cshtml
@model Chevaleresk.Models.Questions

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Questions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idQuestion)

        <div class="form-group">
            @Html.LabelFor(model => model.enonce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.enonce, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.enonce, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idCategorie, "idCategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Chevaleresk/Chevaleresk/Views/Enigma/Index.cshtml
@model IEnumerable<Chevaleresk.Models.Questions>

@{
    ViewBag.Title = "Index";
}
<style>
    .titre {
        margin-bottom: 2%;
    }

    .float-div {
        top: 10%;
        display: flex;
        flex-direction: column;
        align-items: center;
        max-width: 1000px;
        margin: auto;
        background-color: #2F2F2F;
        padding: 50px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
    }

    .boutonEnigma {
        color: white;
        background-color: #2F2F2F;
        text-align: center;
        border-radius: 10px;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 2px;
        padding-bottom: 2px;
        font-family: 'Monda', sans-serif;
        /*        font-weight: bold;*/
        border-color: transparent;
        border-style: solid;
    }

        .boutonEnigma:hover {
            transform: scale(1.05);
            transition: transform 0.3s ease;
            filter: brightness(110%);
        }

    .enigmaText {
        display: flex;
        justify-content: center;
        align-content: center;
        text-align: center;
        font-family: 'Monda';
    }

    .text {
        font-size: 18px;
        color: white;
    }

    .title {
        font-size: 32px;
        color: white;
    }
</style>
<div class="float-div">
    @{
        var userID = Convert.ToInt32(Session["playerID"]);

        var db = new Chevaleresk.Models.ChevalereskEntities();
        var wins = 0;
        var losses = 0;
        double ratio = 0;
        var totalGames = wins + losses;

        if (db.Statistiques.Any(s => s.idJoueur == userID))
        {
            wins = db.Statistiques.Where(s => s.idJoueur == userID).FirstOrDefault().nbQuestionReussi;
            losses = db.Statistiques.Where(s => s.idJoueur == userID).FirstOrDefault().nbQuestionEchoue;
            totalGames = wins + losses;

            if (wins == 0 && losses > 0)
            {
                ratio = 0;
            }
            if (wins > 0 && losses == 0)
            {
                ratio = wins * 100;
            }
            if (wins > 0 && losses > 0)
            {
                ratio = Math.Round((double)wins / totalGames * 100, 2);
            }
        }

    }


    @*<h2 style=" font-size: 48px">Panoramix</h2>*@
    @*<h5 style="color: red; margin-bottom: 20px;">@ViewBag.MsgError</h5>*@
    <h4 class="enigmaText title" style="font-size: 34px;" data-tooltip="Chaque question est rémunérée en fonction de sa difficulté :
- 50 pièces pour une question facile
- 100 pièces pour une question de difficulté moyenne
- 200 pièces pour une question difficile" data-tooltip-location="right">
        Enigma
    </h4>
    <div id="dataEnigma" style="margin-top: 5px;">
        <div id="enigmaStats" style="margin-top: 10px;">

            <div style="display: flex; flex-direction: row; gap: 20px; opacity: 0.9; justify-content: center; text-align: center;">
                <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
                    <span>Victoires</span>
                    <span>@wins</span>
                </div>
                <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
                    <span>Défaites</span>
                    <span>@losses</span>
                </div>
                <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
                    <span>Victoires/Défaites</span>
                    <span>@ratio%</span>
                </div>
            </div>
        </div>
        <hr style="border: 1px solid #D44C4C; width: auto; opacity:0.7;" />
        <span class="enigmaText text fade-effect" style="margin-top: 30px;">Veuillez choisir une difficulté avant de commencer à jouer:</span>

        <div style="display: flex; margin: auto; flex-direction:column;justify-content:center; align-content:center; gap: 10px; margin-top:25px;">
            <button class="boutonEnigma" style="border-width:4px; border-color: #21BB77;" onclick="choisirDifficulte('F')">Facile</button>
            <button class="boutonEnigma" style="border-width: 4px; border-color: #E4D376;" onclick="choisirDifficulte('M')">Moyen</button>
            <button class="boutonEnigma" style="border-width: 4px; border-color: #D44C4C; " onclick="choisirDifficulte('D')">Difficile</button>
            <button class="boutonEnigma" style="border-width: 4px; border-color: #fff;" onclick="choisirDifficulte('R')">Aléatoire</button>
        </div>
    </div>
</div>

@section Scripts{
    <script>


        function choisirDifficulte(id) {
        $.ajax({
            url: '@Url.Action("GetEnigmaQuestion", "Enigma")',
            type: 'GET',
            data: {
                type: id,
            },
            success: function(data) {
                $("#dataEnigma").html(data);
            },
            error: function() {
            }
        });
        };

        function ValidateAnswer(playerId, answerId, type) {

        $.ajax({
            url: '@Url.Action("ValidateEnigmaQuestion", "Enigma")',
            type: 'GET',
            data: {
                idJoueur: playerId,
                idReponse: answerId,
                typeQuestion: type,
            },
            success: function(data) {
                $("#dataEnigma").html(data);
            },
            error: function() {
            }
        });
        };

    </script>
}

Chevaleresk/Chevaleresk/Views/Enigma/QuestionPartial.cshtml
@model Chevaleresk.Models.Questions

@{
    ViewBag.Title = "Jouer";
    var type = Model.type;

    var random = new Random();
    var shuffleAnswers = Model.Reponses.Where(r => r.idQuestion == Model.idQuestion).OrderBy(o => random.Next()).ToList();

    var userID = Convert.ToInt32(Session["playerID"]);

    var db = new Chevaleresk.Models.ChevalereskEntities();
    var wins = 0;
    var losses = 0;
    double ratio = 0;
    var totalGames = wins + losses;

    if (db.Statistiques.Any(s => s.idJoueur == userID))
    {
        wins = db.Statistiques.Where(s => s.idJoueur == userID).FirstOrDefault().nbQuestionReussi;
        losses = db.Statistiques.Where(s => s.idJoueur == userID).FirstOrDefault().nbQuestionEchoue;
        totalGames = wins + losses;

        if (wins == 0 && losses > 0)
        {
            ratio = 0;
        }
        if (wins > 0 && losses == 0)
        {
            ratio = wins * 100;
        }
        if (wins > 0 && losses > 0)
        {
            ratio = Math.Round((double)wins / totalGames * 100, 2);
        }
    }
}
<div id="enigmaStats" style="margin-top: 10px;">

    <div style="display: flex; flex-direction: row; gap: 20px; opacity: 0.9; justify-content: center; text-align: center;">
        <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
            <span>Victoires</span>
            <span>@wins</span>
        </div>
        <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
            <span>Défaites</span>
            <span>@losses</span>
        </div>
        <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
            <span>Victoires/Défaites</span>
            <span>@ratio%</span>
        </div>
    </div>
</div>
<hr style="border: 1px solid #D44C4C; width: auto; opacity:0.7;" />
<span class="enigmaText text" style="display: flex; justify-content:center; font-style:italic"> @Html.DisplayFor(model => model.Categories.nomCategorie)</span>
<span class="enigmaText text" style="margin-top: 30px;">@Html.DisplayFor(model => model.enonce)</span>
<div style="display: flex; flex-direction: column; gap: 10px; margin-top: 20px;">
    @*@foreach (var reponses in Model.Reponses.Where(r => r.idQuestion == Model.idQuestion).ToList())*@
    @foreach (var reponses in shuffleAnswers)
    {
        <button class="boutonEnigma" style="background-color: #D44C4C;" onclick="ValidateAnswer(@Convert.ToInt32(Session["playerID"]), @reponses.idReponse, '@type')">@reponses.laReponse</button>
    }
</div>

Chevaleresk/Chevaleresk/Views/Enigma/ValidatePartial.cshtml
@model Chevaleresk.Models.Questions

@{
    ViewBag.Title = "Jouer";

    var userID = Convert.ToInt32(Session["playerID"]);

    var db = new Chevaleresk.Models.ChevalereskEntities();
    var wins = 0;
    var losses = 0;
    double ratio = 0;
    var totalGames = wins + losses;

    if (db.Statistiques.Any(s => s.idJoueur == userID))
    {
        wins = db.Statistiques.Where(s => s.idJoueur == userID).FirstOrDefault().nbQuestionReussi;
        losses = db.Statistiques.Where(s => s.idJoueur == userID).FirstOrDefault().nbQuestionEchoue;
        totalGames = wins + losses;

        if (wins == 0 && losses > 0)
        {
            ratio = 0;
        }
        if (wins > 0 && losses == 0)
        {
            ratio = wins * 100;
        }
        if (wins > 0 && losses > 0)
        {
            ratio = Math.Round((double)wins / totalGames * 100, 2);
        }
    }


}
<div id="enigmaStats" style="margin-top: 10px;">

    <div style="display: flex; flex-direction: row; gap: 20px; opacity: 0.9; justify-content: center; text-align: center;">
        <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
            <span>Victoires</span>
            <span>@wins</span>
        </div>
        <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
            <span>Défaites</span>
            <span>@losses</span>
        </div>
        <div class="enigmaText" style="display: flex; flex-direction: column; justify-content: center; text-align: center;">
            <span>Victoires/Défaites</span>
            <span>@ratio%</span>
        </div>
    </div>
</div>
<div style="display: flex; flex-direction: column; gap: 14px; margin-top: 20px; justify-content:center; align-content:center; margin: auto;">
    <hr style="border: 1px solid #D44C4C; width: auto; opacity:0.7;" />
    @if ((bool)TempData["playerWon"])
    {
        <p class="enigmaText title" style="margin-top: 3px;">Bonne réponse ✅</p>
        <p class="enigmaText text">
            Félicitation! <br />
            @TempData["winningMessage"].ToString()
        </p>
        <button class="bouton" onClick="location.reload() " style="background-color: #D44C4C">Retourner au menu</button>
    }
    else
    {
        <p class="enigmaText title" style="margin-top: 3px;">Mauvaise réponse ❌</p>
        <p class="enigmaText text">Vous avez perdu...</p>
        <button class="bouton" onClick="location.reload() " style="background-color: #D44C4C">Retourner au menu</button>
    }
</div>